.build_default:
  stage: build
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - node_modules/
      - lib/

.test_default:
  stage: test
  script:
    - npm run ci

stages:
  - build
  - test
  - integration

cache:
  paths:
  - node_modules/

"node build v12":
  image: node:12-alpine
  extends: .build_default

"node test v12":
  image: node:12-alpine
  extends: .test_default
  dependencies:
    - node build v12

"node build v14":
  image: node:14-alpine
  extends: .build_default

"node test v14":
  image: node:14-alpine
  extends: .test_default
  dependencies:
    - node build v14

"node build v16":
  image: node:16-alpine
  extends: .build_default

"node test v16":
  image: node:16-alpine
  extends: .test_default
  dependencies:
    - node build v16

"example integration testing":
  stage: integration
  image: node:16-alpine
  dependencies:
    - node build v16
  before_script:
    - "npx ts-node test/util/server.ts &"
  script:
    - "cd examples/imdb-api-react && yarn && yarn test; cd ../.."
    - "cd examples/imdb-api-node && npm install && node index.js; cd ../.."
